# Generated by Django 3.0.2 on 2020-02-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
