# Generated by Django 3.0.2 on 2020-02-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twdata', '0002_auto_20200202_1308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweets',
            unique_together={('author', 'text', 'date', 'likes_count', 'hashtags', 'replies_count', 'retweets_count')},
        ),
    ]
