# Generated by Django 3.0.2 on 2020-02-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twdata', '0003_auto_20200202_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persons',
            name='followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persons',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twdata.Persons'),
        ),
    ]
